/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.64
 * Generated at: 2022-07-18 08:48:23 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class insertStd_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=ISO-8859-1");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html>\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<title>W3.CSS Template</title>\r\n");
      out.write("<meta charset=\"UTF-8\">\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://www.w3schools.com/w3css/4/w3.css\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://fonts.googleapis.com/css?family=Montserrat\">\r\n");
      out.write("<link rel=\"stylesheet\" href=\"https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css\">\r\n");
      out.write("<link href=\"CSS/insertStd.css\" rel=\"stylesheet\" type=\"text/css\"/>\r\n");
      out.write("<style>\r\n");
      out.write("\r\n");
      out.write("body, h1,h2,h3,h4,h5,h6 {font-family: \"Montserrat\", sans-serif}\r\n");
      out.write(".w3-row-padding img {margin-bottom: 12px}\r\n");
      out.write("/* Set the width of the sidebar to 120px */\r\n");
      out.write(".w3-sidebar {width: 120px;background: #222;}\r\n");
      out.write("/* Add a left margin to the \"page content\" that matches the width of the sidebar (120px) */\r\n");
      out.write("#main {margin-left: 120px}\r\n");
      out.write("/* Remove margins from \"page content\" on small screens */\r\n");
      out.write("@media only screen and (max-width: 600px) {#main {margin-left: 0}}\r\n");
      out.write("</style>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"w3-black\">\r\n");
      out.write("\r\n");
      out.write("<!-- Icon Bar (Sidebar - hidden on small screens) -->\r\n");
      out.write("<nav class=\"w3-sidebar w3-bar-block w3-small w3-hide-small w3-center\">\r\n");
      out.write("\r\n");
      out.write("  <a href=\"#\" class=\"w3-bar-item w3-button w3-padding-large w3-black\">\r\n");
      out.write("    <i class=\"fa fa-home w3-xxlarge\"></i>\r\n");
      out.write("    <p>HOME</p>\r\n");
      out.write("  </a>\r\n");
      out.write("  <a href=\"insertStd.jsp\" class=\"w3-bar-item w3-button w3-padding-large w3-hover-black\">\r\n");
      out.write("    <i class=\"fa fa-user w3-xxlarge\"></i>\r\n");
      out.write("    <p>Registraion</p>\r\n");
      out.write("  </a>\r\n");
      out.write("  <a href=\"#photos\" class=\"w3-bar-item w3-button w3-padding-large w3-hover-black\">\r\n");
      out.write("    <i class=\"fa fa-eye w3-xxlarge\"></i>\r\n");
      out.write("    <p>PHOTOS</p>\r\n");
      out.write("  </a>\r\n");
      out.write("  <a href=\"#contact\" class=\"w3-bar-item w3-button w3-padding-large w3-hover-black\">\r\n");
      out.write("    <i class=\"fa fa-envelope w3-xxlarge\"></i>\r\n");
      out.write("    <p>CONTACT</p>\r\n");
      out.write("  </a>\r\n");
      out.write("</nav>\r\n");
      out.write("\r\n");
      out.write("<!-- Navbar on small screens (Hidden on medium and large screens) -->\r\n");
      out.write("<div class=\"w3-top w3-hide-large w3-hide-medium\" id=\"myNavbar\">\r\n");
      out.write("  <div class=\"w3-bar w3-black w3-opacity w3-hover-opacity-off w3-center w3-small\">\r\n");
      out.write("    <a href=\"#\" class=\"w3-bar-item w3-button\" style=\"width:25% !important\">HOME</a>\r\n");
      out.write("    <a href=\"#about\" class=\"w3-bar-item w3-button\" style=\"width:25% !important\">ABOUT</a>\r\n");
      out.write("    <a href=\"#photos\" class=\"w3-bar-item w3-button\" style=\"width:25% !important\">PHOTOS</a>\r\n");
      out.write("    <a href=\"#contact\" class=\"w3-bar-item w3-button\" style=\"width:25% !important\">CONTACT</a>\r\n");
      out.write("  </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<!-- Page Content -->\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    	<h1>Register new Student</h1>\r\n");
      out.write("\r\n");
      out.write("	<form action=\"insert\" method=\"post\" class=\"form\">\r\n");
      out.write("	\r\n");
      out.write("  <!-- 2 column grid layout with text inputs for the first and last names -->\r\n");
      out.write("  <div class=\"row mb-4\">\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"form-outline\">\r\n");
      out.write("        <input type=\"text\" id=\"form3Example1\" class=\"form-control\" />\r\n");
      out.write("        <label class=\"form-label\" for=\"form3Example1\">Name</label>\r\n");
      out.write("      </div><br><br>\r\n");
      out.write("    </div>\r\n");
      out.write("    <div class=\"col\">\r\n");
      out.write("      <div class=\"form-outline\">\r\n");
      out.write("        <input type=\"text\" id=\"form3Example2\" class=\"form-control\" />\r\n");
      out.write("        <label class=\"form-label\" for=\"form3Example2\">Last name</label>\r\n");
      out.write("      </div><br><br>\r\n");
      out.write("    </div>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Email input -->\r\n");
      out.write("  <div class=\"form-outline mb-4\">\r\n");
      out.write("    <input type=\"email\" id=\"form3Example3\" class=\"form-control\" />\r\n");
      out.write("    <label class=\"form-label\" for=\"form3Example3\">Email address</label>\r\n");
      out.write("  </div><br><br>\r\n");
      out.write("\r\n");
      out.write("  <!-- Password input -->\r\n");
      out.write("  <div class=\"form-outline mb-4\">\r\n");
      out.write("    <input type=\"password\" id=\"form3Example4\" class=\"form-control\" />\r\n");
      out.write("    <label class=\"form-label\" for=\"form3Example4\">Password</label>\r\n");
      out.write("  </div><br><br>\r\n");
      out.write("\r\n");
      out.write("  <!-- Checkbox -->\r\n");
      out.write("  <div class=\"form-check d-flex justify-content-center mb-4\">\r\n");
      out.write("    <input class=\"form-check-input me-2\" type=\"checkbox\" value=\"\" id=\"form2Example33\" checked />\r\n");
      out.write("    <label class=\"form-check-label\" for=\"form2Example33\">\r\n");
      out.write("      Subscribe to our newsletter\r\n");
      out.write("    </label>\r\n");
      out.write("  </div>\r\n");
      out.write("\r\n");
      out.write("  <!-- Submit button -->\r\n");
      out.write("  <button type=\"submit\" class=\"btn btn-primary btn-block mb-4\">Sign up</button>\r\n");
      out.write("\r\n");
      out.write("  <!-- Register buttons -->\r\n");
      out.write("  <div class=\"text-center\">\r\n");
      out.write("    <p>or sign up with:</p>\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary btn-floating mx-1\">\r\n");
      out.write("      <i class=\"fab fa-facebook-f\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary btn-floating mx-1\">\r\n");
      out.write("      <i class=\"fab fa-google\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary btn-floating mx-1\">\r\n");
      out.write("      <i class=\"fab fa-twitter\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("\r\n");
      out.write("    <button type=\"button\" class=\"btn btn-primary btn-floating mx-1\">\r\n");
      out.write("      <i class=\"fab fa-github\"></i>\r\n");
      out.write("    </button>\r\n");
      out.write("  </div>\r\n");
      out.write("</form>\r\n");
      out.write("   \r\n");
      out.write("    \r\n");
      out.write("   \r\n");
      out.write("\r\n");
      out.write("  <!-- Contact Section -->\r\n");
      out.write("  <div class=\"w3-padding-64 w3-content w3-text-grey\" id=\"contact\">\r\n");
      out.write("    <h2 class=\"w3-text-light-grey\">Contact Me</h2>\r\n");
      out.write("    <hr style=\"width:200px\" class=\"w3-opacity\">\r\n");
      out.write("\r\n");
      out.write("    <div class=\"w3-section\">\r\n");
      out.write("      <p><i class=\"fa fa-map-marker fa-fw w3-text-white w3-xxlarge w3-margin-right\"></i> Chicago, US</p>\r\n");
      out.write("      <p><i class=\"fa fa-phone fa-fw w3-text-white w3-xxlarge w3-margin-right\"></i> Phone: +00 151515</p>\r\n");
      out.write("      <p><i class=\"fa fa-envelope fa-fw w3-text-white w3-xxlarge w3-margin-right\"> </i> Email: mail@mail.com</p>\r\n");
      out.write("    </div><br>\r\n");
      out.write("     <!-- End Contact Section -->\r\n");
      out.write("  </div>\r\n");
      out.write("  \r\n");
      out.write("    <!-- Footer -->\r\n");
      out.write("  <footer class=\"w3-content w3-padding-64 w3-text-grey w3-xlarge\">\r\n");
      out.write("    <i class=\"fa fa-facebook-official w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-instagram w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-snapchat w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-pinterest-p w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-twitter w3-hover-opacity\"></i>\r\n");
      out.write("    <i class=\"fa fa-linkedin w3-hover-opacity\"></i>\r\n");
      out.write("    <p class=\"w3-medium\">Powered by <a href=\"https://www.w3schools.com/w3css/default.asp\" target=\"_blank\" class=\"w3-hover-text-green\">w3.css</a></p>\r\n");
      out.write("  <!-- End footer -->\r\n");
      out.write("  </footer>\r\n");
      out.write("\r\n");
      out.write("<!-- END PAGE CONTENT -->\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
